name: Scrape
# Controls when the action will run.
on:
  schedule:
    - cron:  '47 18 * * *' #UTC Time, represents 12:47 pm Pacific
  workflow_dispatch:

jobs:
  auto-scrape:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
      
      - name: Set up R
        uses: r-lib/actions/setup-r@v2

      - name: Install packages
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          packages: |
            any::dplyr
            any::tidyr
            any::stringr
            any::rvest
            any::janitor 

      - name: Run R Script
        run: Rscript -e 'source("aaa_gas_scraper_GITHUB.R")'
       
      - name: Add and commit	
        run: |
          git add .	
          git config user.name "Automated"	
          git config user.email "actions@users.noreply.github.com"	
          git commit -m "Latest data" 	
          
      - name: Push	
        run: git push
